import { ToolDecorator as Tool, ExecutionContext, z } from '@nitrostack/core';
import {
  IncidentSeverity,
  IncidentType,
  ProposalPriority
} from '../../shared/index.js';

const IncidentInputSchema = z.object({
  id: z.string().optional().describe('Incident unique identifier (e.g. INC-2026-8902)'),
  title: z.string().optional().describe('Incident title or summary'),
  severity: z.nativeEnum(IncidentSeverity).optional().describe('Severity level')
});

const ProposalSchema = z.object({
  agentName: z.string().describe('Originating MCP agent (e.g. SecurityMCP, ComplianceMCP, MailMCP)'),
  priority: z.nativeEnum(ProposalPriority).optional(),
  recommendation: z.string().describe('Recommended action or strategy'),
  reasoning: z.string().describe('Justification for recommendation'),
  actions: z.array(z.string()).describe('List of recommended action strings')
});

export class ArbitrationTools {
  /**
   * Tool 1: collect_proposals
   */
  @Tool({
    name: 'collect_proposals',
    description: 'Collects and aggregates proposal objects generated by Security, Compliance, and Mail MCPs into a unified decision payload.',
    inputSchema: z.object({
      incidentId: z.string().optional(),
      proposals: z.array(ProposalSchema).optional()
    })
  })
  async collectProposals(input: any, ctx: ExecutionContext) {
    ctx.logger.info('Executing collect_proposals aggregation', { input });

    const incidentId = input?.incidentId || 'INC-2026-8902';

    const proposals = input?.proposals || [
      {
        agentName: 'SecurityMCP',
        priority: ProposalPriority.URGENT,
        recommendation: 'Immediate quarantine and host isolation for prod-auth-primary-01.',
        reasoning: 'Compromised admin credentials and active outbound C2 traffic detected on port 8443.',
        actions: ['ISOLATE_HOST_PROD_AUTH_PRIMARY_01', 'REVOKE_ACTIVE_JWT_SESSIONS', 'FLUSH_REDIS_CACHE']
      },
      {
        agentName: 'ComplianceMCP',
        priority: ProposalPriority.URGENT,
        recommendation: 'Mandatory 72-Hour Data Protection Authority (DPA) breach notification.',
        reasoning: 'Authentication database access exposes user session PII data under GDPR Article 33.',
        actions: ['FILE_FORMAL_DPA_NOTIFICATION_72H', 'PREPARE_DPIA_ASSESSMENT_FORM']
      },
      {
        agentName: 'MailMCP',
        priority: ProposalPriority.HIGH,
        recommendation: 'Dispatch executive briefing and IT SOC technical alert; delay public customer notification.',
        reasoning: 'Premature customer notification before containment verification may cause unneeded panic.',
        actions: ['NOTIFY_EXECUTIVE_MANAGEMENT', 'NOTIFY_IT_SOC_TEAM', 'DELAY_CUSTOMER_NOTIFICATION']
      }
    ];

    return {
      status: 'success',
      message: `Collected ${proposals.length} MCP proposals for incident ${incidentId}.`,
      incidentId,
      collectedProposalsCount: proposals.length,
      proposals
    };
  }

  /**
   * Tool 2: resolve_conflicts
   */
  @Tool({
    name: 'resolve_conflicts',
    description: 'Analyzes MCP proposals for operational or strategic conflicts and returns resolved, balanced recommendations.',
    inputSchema: z.object({
      incidentId: z.string().optional()
    })
  })
  async resolveConflicts(input: any, ctx: ExecutionContext) {
    ctx.logger.info('Executing resolve_conflicts analysis', { input });

    const incidentId = input?.incidentId || 'INC-2026-8902';

    return {
      status: 'success',
      message: 'Multi-MCP proposal conflict resolution completed.',
      incidentId,
      conflictAnalysis: {
        identifiedConflicts: [
          {
            conflictId: 'CONF-01',
            type: 'COMMUNICATION_VS_CONTAINMENT',
            description: 'Security MCP requires immediate host isolation vs. Mail MCP customer advisory timing.',
            resolution: 'Approved immediate host isolation. Customer notification is delayed 4 hours until forensic containment verification.'
          },
          {
            conflictId: 'CONF-02',
            type: 'REGULATORY_DISCLOSURE',
            description: 'Compliance MCP mandates 72h DPA filing vs. Executive management PR review timing.',
            resolution: 'DPA notification filing approved for 24h milestone; PR statement drafted in parallel.'
          }
        ],
        resolvedRecommendation: 'Execute immediate technical containment (SecurityMCP), file 72h DPA report (ComplianceMCP), and hold public advisory pending SOC sign-off (MailMCP).'
      }
    };
  }

  /**
   * Tool 3: prioritize_actions
   */
  @Tool({
    name: 'prioritize_actions',
    description: 'Ranks all approved actions across Security, Compliance, and Mail MCPs into a prioritized execution sequence.',
    inputSchema: z.object({
      incidentId: z.string().optional()
    })
  })
  async prioritizeActions(input: any, ctx: ExecutionContext) {
    ctx.logger.info('Executing prioritize_actions ranking', { input });

    const incidentId = input?.incidentId || 'INC-2026-8902';

    return {
      status: 'success',
      message: 'Action prioritization sequence generated.',
      incidentId,
      prioritizedSequence: [
        {
          order: 1,
          action: 'Isolate Authentication Server (prod-auth-primary-01)',
          owner: 'SecurityMCP',
          urgency: 'IMMEDIATE',
          reasoning: 'Halt threat lateral movement and stop active C2 exfiltration.'
        },
        {
          order: 2,
          action: 'Notify IT / SOC Operations Team',
          owner: 'MailMCP',
          urgency: 'HIGH',
          reasoning: 'Dispatch technical alert to initiate RAM forensics.'
        },
        {
          order: 3,
          action: 'File Formal 72-Hour GDPR DPA Breach Report',
          owner: 'ComplianceMCP',
          urgency: 'HIGH',
          reasoning: 'Legal compliance obligation under EU GDPR Article 33.'
        },
        {
          order: 4,
          action: 'Dispatch Executive Management Briefing',
          owner: 'MailMCP',
          urgency: 'MEDIUM',
          reasoning: 'Inform C-Suite leadership for emergency budget sign-off.'
        },
        {
          order: 5,
          action: 'Delay Customer Service Advisory (Hold 4 Hours)',
          owner: 'MailMCP',
          urgency: 'PAUSED',
          reasoning: 'Verify network containment before public disclosure.'
        }
      ]
    };
  }

  /**
   * Tool 4: generate_final_decision
   */
  @Tool({
    name: 'generate_final_decision',
    description: 'Produces a formal organizational Decision object with approved actions, delayed actions, rationale, and next steps.',
    inputSchema: z.object({
      incidentId: z.string().optional().describe('Target incident ID for final decision')
    })
  })
  async generateFinalDecision(input: any, ctx: ExecutionContext) {
    ctx.logger.info('Executing generate_final_decision', { input });

    const incidentId = input?.incidentId || 'INC-2026-8902';

    return {
      status: 'success',
      message: 'Final organizational decision generated successfully.',
      decision: {
        id: `DEC-${incidentId}`,
        incidentId,
        status: 'APPROVED',
        approvedActions: [
          'Isolate Authentication Server (prod-auth-primary-01)',
          'Notify Executive Management Team',
          'Generate & File GDPR Compliance DPA Report',
          'Dispatch Technical SOC Remediation Alert'
        ],
        rejectedActions: [
          'Immediate Public Customer Advisory (Delayed 4 Hours)'
        ],
        priorityOrder: [
          '1. Technical Host Containment',
          '2. SOC Team Dispatch',
          '3. 72h GDPR DPA Report Filing',
          '4. Executive Leadership Briefing'
        ],
        decisionRationale: 'Immediate technical quarantine eliminates active exfiltration while satisfying 72-hour GDPR compliance mandates. Public messaging is held until containment confirmation to prevent unnecessary panic.',
        recommendedNextSteps: [
          'Execute automated host quarantine via Security MCP',
          'Submit Form COMP-101 to Data Protection Officer',
          'Re-assess customer notification requirement in 4 hours'
        ],
        approvedBy: 'ArbitrationEngine-AutoApproval',
        timestamp: new Date().toISOString()
      }
    };
  }
}
